# Generated by Django 6.0.5 on 2026-05-09 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name_plural": "Kategori",
            },
        ),
        migrations.CreateModel(
            name="Lokasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gedung", models.CharField(max_length=100)),
                ("lantai", models.CharField(blank=True, max_length=50, null=True)),
                ("ruangan", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "Lokasi",
            },
        ),
        migrations.CreateModel(
            name="Laporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deskripsi", models.TextField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="laporan_foto/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("processed", "Diproses"),
                            ("completed", "Selesai"),
                            ("rejected", "Ditolak"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "prioritas",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("medium", "Sedang"),
                            ("high", "Tinggi"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("tanggal_dibuat", models.DateTimeField(auto_now_add=True)),
                ("tanggal_diproses", models.DateTimeField(blank=True, null=True)),
                ("tanggal_selesai", models.DateTimeField(blank=True, null=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.kategori",
                    ),
                ),
                (
                    "pelapor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laporan_dibuat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teknisi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laporan_ditangani",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lokasi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.lokasi",
                    ),
                ),
            ],
            options={
                "ordering": ["-tanggal_dibuat"],
            },
        ),
        migrations.CreateModel(
            name="UpdateLaporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("catatan", models.TextField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="update_foto/"),
                ),
                ("tanggal_dibuat", models.DateTimeField(auto_now_add=True)),
                (
                    "laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="reports.laporan",
                    ),
                ),
            ],
        ),
    ]
