# Generated by Django 6.0.5 on 2026-05-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="laporan",
            options={"ordering": ["-tanggal_dibuat"], "verbose_name_plural": "Laporan"},
        ),
        migrations.AlterModelOptions(
            name="updatelaporan",
            options={"verbose_name_plural": "Update Laporan"},
        ),
    ]
